# Конфигурация Poetry для конкретного проекта
[virtualenvs]
# Настройка: не создавать собственное виртуальное окружение .venv внутри папки проекта.
# Это полезно при работе в Docker или если вы уже создали окружение вручную.
create = false
